/**
 * The German catalogue. Typed against the English keys, so a key missing
 * here is a compile error, not a silent fallback. SPEC.md §14.1.
 */
import type { EN } from './catalogue-en.js';

export const DE: Readonly<Record<keyof typeof EN, string>> = {
  'view.explorer': 'Explorer',
  'view.sourceControl': 'Versionsverwaltung',
  'view.inspector': 'Inspektor',
  'view.outline': 'Gliederung',
  'view.ai': 'KI-Assistent',
  'view.snapshots': 'Schnappschüsse',
  'view.settings': 'Einstellungen',

  'app.noProject': 'Kein Projekt geöffnet.',
  'app.readOnly': 'schreibgeschützt',
  'app.refresh': 'Aktualisieren',
  'app.reload': 'Von der Platte neu laden',
  'app.frontMatter.show': 'Variablen',
  'app.frontMatter.writable': 'Bearbeitbar',
  'app.frontMatter.system': 'System',
  'app.frontMatter.foreign': 'Fremde Variablen',
  'app.frontMatter.own': 'Eigene Variablen',
  'app.selectSheet': 'Wähle ein Blatt, um zu schreiben.',
  'app.outline.deeper': 'H3–H6',
  'app.outline.deeperTitle': 'H3 bis H6 anzeigen',
  'app.notBuilt': 'Noch nicht gebaut.',
  'app.ignore.title': 'Ignorierte Dateien',
  'app.ignore.hint': 'Ein Pfad oder Muster je Zeile, so wie git sie liest.',
  'app.conflict.title': 'Dieses Blatt hat sich auf der Platte geändert, während du es bearbeitet hast',
  'app.conflict.warning': 'Die Datei zu laden verwirft, was du nicht gespeichert hast.',
  'app.conflict.hint':
    'Deine Fassung zu behalten ändert nichts auf der Platte; ein späteres Speichern überschreibt die Datei.',
  'app.conflict.confirm': 'Datei laden',
  'app.dismiss': 'Ausblenden',

  'common.cancel': 'Abbrechen',
  'common.close': 'Schließen',
  'common.open': 'Öffnen',
  'common.save': 'Speichern',
  'common.create': 'Anlegen',
  'common.rename': 'Umbenennen',
  'common.delete': 'Löschen',
  'common.discard': 'Verwerfen',
  'confirm.trashHint': 'Es landet im Papierkorb des Systems und kann von dort zurückgeholt werden.',

  'heading.none': 'Keine Überschrift',
  'statusBar.position': 'Z. {line}, Sp. {column}',
  'statusBar.positionLabel': 'Cursorposition',
  'statusBar.wrap': 'Umbruch',
  'statusBar.wrapTitle': 'Lange Zeilen in diesem Blatt umbrechen',
  'outline.empty': 'Keine Überschriften in diesem Blatt.',
  'sheetList.empty': 'Keine Blätter in dieser Gruppe.',

  'inspector.words.one': 'Wort',
  'inspector.words.other': 'Wörter',
  'inspector.characters.one': 'Zeichen',
  'inspector.characters.other': 'Zeichen',
  'inspector.minutes.one': 'Min. Lesezeit',
  'inspector.minutes.other': 'Min. Lesezeit',
  'inspector.title': 'Titel',
  'inspector.topic': 'Thema',
  'inspector.topicPlaceholder': 'ein kurzes Stichwort',
  'inspector.keywords': 'Schlagwörter',
  'inspector.keywordsPlaceholder': 'durch Kommas getrennt',
  'inspector.status': 'Status',
  'inspector.category': 'Kategorie',
  'inspector.noCategory': 'Keine',
  'inspector.manage': 'Verwalten…',
  'inspector.notes': 'Notizen',
  'inspector.notesPlaceholder': 'Recherche, offene Fragen, Erinnerungen',
  'inspector.noSheet': 'Kein Blatt geöffnet.',

  'categories.title': 'Seitenkategorien',
  'categories.empty': 'Noch keine Kategorien.',
  'categories.add': 'Hinzufügen',
  'categories.colourOf': 'Farbe von {name}',
  'categories.name': 'Name der Kategorie',
  'categories.delete': 'Kategorie löschen',
  'categories.unnamed': 'Unbenannt',
  'categories.new': 'Neue Kategorie',
  'categories.limit': 'Ein Projekt hat höchstens {limit} Kategorien.',

  'library.menu.newSheet': 'Neues Blatt…',
  'library.menu.newGroup': 'Neue Gruppe…',
  'library.menu.rename': 'Umbenennen…',
  'library.menu.deleteGroup': 'Gruppe löschen…',
  'library.menu.deleteSheet': 'Blatt löschen…',
  'library.newSheet.title': 'Neues Blatt',
  'library.newSheet.placeholder': 'Die erste Szene',
  'library.newSheet.hint': 'Der Titel kann sich später ändern; der Dateiname wird einmal daraus gebildet.',
  'library.newGroup.title': 'Neue Gruppe',
  'library.newGroup.placeholder': 'Erster Teil',
  'library.newGroup.hint': 'Der Name kann sich später ändern; der Ordnername wird einmal daraus gebildet.',
  'library.renameGroup.title': 'Gruppe umbenennen',
  'library.renameGroup.hint': 'Umbenennen ändert den Namen hier, nie den Ordner auf der Platte.',
  'library.renameSheet.title': 'Blatt umbenennen',
  'library.renameSheet.hint': 'Umbenennen ändert den Titel in der Datei, nie den Dateinamen.',
  'library.trash.title': '„{name}“ in den Papierkorb legen?',
  'library.trash.unsaved': 'Es hat ungespeicherte Änderungen, und die sind danach nicht im Papierkorb.',
  'library.trash.contents': 'Alles darin geht mit: {parts}.',
  'library.trash.and': ' und ',
  'library.sheets.one': '{count} Blatt',
  'library.sheets.other': '{count} Blätter',
  'library.subgroups.one': '{count} Untergruppe',
  'library.subgroups.other': '{count} Untergruppen',

  'sourceControl.noRepository': 'Dieses Projekt liegt in keinem Git-Repository.',
  'sourceControl.createRepository': 'Repository anlegen',
  'sourceControl.reading': 'Lese…',
  'sourceControl.onBranch': 'Auf Branch {name}',
  'sourceControl.branches': 'Branches…',
  'sourceControl.notPublished': '{branch} — nicht veröffentlicht',
  'sourceControl.publish': 'Branch veröffentlichen…',
  'sourceControl.tracking': 'Folgt {upstream}',
  'sourceControl.upToDate': 'auf dem neuesten Stand',
  'sourceControl.fetch': 'Abrufen',
  'sourceControl.pull': 'Pull',
  'sourceControl.merge': 'Zusammenführen…',
  'sourceControl.merging': 'Zusammenführung läuft. Entscheide jeden Konflikt, dann committe.',
  'sourceControl.abortMerge': 'Zusammenführung abbrechen',
  'sourceControl.noAuthor': 'Commits haben noch keinen Autor.',
  'sourceControl.setIdentity': 'Festlegen…',
  'sourceControl.ignoredFiles': 'Ignorierte Dateien…',
  'sourceControl.stageAll': 'Alle Änderungen vormerken',
  'sourceControl.changes': 'Änderungen ({count})',
  'sourceControl.stage': '{path} vormerken',
  'sourceControl.ignore': '{path} ignorieren',
  'sourceControl.ignoreTitle': 'In .gitignore aufnehmen',
  'sourceControl.resolve': '{path} auflösen',
  'sourceControl.resolveTitle': 'Diesen Konflikt auflösen',
  'sourceControl.resolveButton': 'Auflösen…',
  'sourceControl.showChanges': 'Änderungen an {path} zeigen',
  'sourceControl.showChangesTitle': 'Änderungen zeigen',
  'sourceControl.discardChanges': 'Änderungen an {path} verwerfen',
  'sourceControl.discardTitle': 'Änderungen verwerfen',
  'sourceControl.nothingChanged': 'Nichts hat sich geändert.',
  'sourceControl.messagePlaceholder': 'Commit-Nachricht',
  'sourceControl.amend': 'Letzten Commit ersetzen…',
  'sourceControl.commit': 'Commit',
  'sourceControl.commitAndPush': 'Commit und Push',
  'sourceControl.gitNotInstalled':
    'Git ist auf diesem Rechner nicht installiert oder nicht im Pfad. Die Versionsverwaltung braucht es; alles andere geht ohne.',

  'discard.title': 'Die Änderungen an „{path}“ verwerfen?',
  'discard.untracked':
    'Diese Datei ist noch nicht im Repository, es gibt also nichts, wohin sie zurückkönnte: Sie landet im Papierkorb.',
  'discard.tracked':
    'Die Datei geht auf ihren letzten Commit zurück, und ungespeicherte Änderungen daran im Editor gehen mit.',
  'discard.historyHint': 'Die committete Fassung bleibt so oder so in der Geschichte des Repositorys.',
  'merge.title': 'Die Änderungen der Gegenseite zusammenführen?',
  'merge.warning': 'Wo beide Seiten dieselbe Stelle geändert haben, entscheidest du, welche Fassung bleibt.',
  'merge.hint': 'Eine Zusammenführung lässt sich danach abbrechen; dann ist alles wieder wie zuvor.',
  'merge.confirm': 'Zusammenführen',
  'publish.title': 'Diesen Branch veröffentlichen',
  'publish.placeholder': 'https://example.com/buch.git',
  'publish.hint': 'Die Adresse eines leeren Repositorys. Sie wird als „origin“ eingetragen.',
  'publish.confirm': 'Veröffentlichen',
  'publish.toTitle': '„{branch}“ nach {remote} veröffentlichen?',
  'publish.toWarning': 'Alles, was auf diesem Branch committet ist, geht an {url}.',
  'publish.toHint': 'Von da an geht „Commit und Push“ dorthin, ohne noch einmal zu fragen.',
  'switch.title': 'Erst speichern oder verwerfen',
  'switch.warning': '„{title}“ hat Änderungen, die nicht gespeichert sind.',
  'switch.hint': 'Ein Branch-Wechsel ersetzt Dateien auf der Platte, und ungespeicherte Arbeit hat keinen Platz.',
  'switch.confirm': 'Speichern und wechseln',
  'newBranch.title': 'Neuer Branch',
  'newBranch.placeholder': 'entwurf/kapitel-3',
  'newBranch.hint': 'Er beginnt beim aktuellen Commit und wird sofort ausgecheckt.',
  'deleteBranch.title': 'Den Branch „{name}“ löschen?',
  'deleteBranch.warning':
    'Nur ein Branch, dessen Arbeit schon zusammengeführt ist, lässt sich löschen; alles andere verweigert git.',
  'deleteBranch.hint': 'Die Commits bleiben so oder so im Repository.',
  'amend.title': 'Den letzten Commit ersetzen?',
  'amend.warning': 'Er wird mit dem Vorgemerkten neu geschrieben, und seine Nachricht wird „{message}“.',
  'amend.hint': 'Nur solange er nicht gepusht ist; danach ließe er sich nur mit Gewalt ersetzen.',
  'amend.confirm': 'Ersetzen',

  'branches.title': 'Branches',
  'branches.new': 'Neuer Branch…',
  'branches.checkedOut': 'ausgecheckt',
  'branches.switch': 'Wechseln',
  'branches.delete': 'Löschen…',
  'branches.empty': 'Dieses Repository hat noch keinen Branch.',

  'resolver.label': '{path} auflösen',
  'resolver.decided': '{decided} von {total} entschieden',
  'resolver.apply': 'Übernehmen',
  'resolver.keepMine': 'Meine behalten',
  'resolver.takeTheirs': 'Ihre nehmen',

  'diff.words': 'Wörter',
  'diff.lines': 'Zeilen',
  'diff.nothing': 'Nichts hat sich in dieser Datei geändert.',
  'diff.gitNothing': 'Git meldet keinen Unterschied für diese Datei.',
  'diff.wordsLabel': 'Änderungen, Wort für Wort',
  'diff.label': 'Diff',

  'identity.title': 'Name und E-Mail für Commits',
  'identity.name': 'Name',
  'identity.email': 'E-Mail',
  'identity.hint':
    'Beides steht in jedem Commit und geht mit dem Manuskript, wohin es auch veröffentlicht wird. Beides wird nur in diesem Projekt eingetragen; außerhalb ändert sich nichts.',
  'identity.notNow': 'Jetzt nicht',

  'settings.title': 'Einstellungen',
  'settings.categories': 'Kategorien der Einstellungen',
  'settings.manageCategories': 'Kategorien verwalten…',
  'settings.identity.local': 'In diesem Repository eingetragen.',
  'settings.identity.global':
    'Aus deiner globalen Git-Konfiguration; hier zu speichern trägt eine Kopie in dieses Repository ein.',
  'settings.identity.none': 'Commits haben noch keinen Autor.',
  'settings.reset': 'Alle Einstellungen zurücksetzen',
  'settings.applyNote': 'Änderungen wirken sofort und gelten für diese Installation.',
  'settings.category.appearance.label': 'Darstellung',
  'settings.category.appearance.description': 'Die Sprache, in der die Oberfläche spricht.',
  'settings.category.editor.label': 'Editor',
  'settings.category.editor.description': 'Wie sich der Text beim Schreiben liest.',
  'settings.editor.fontFamily': 'Schrift',
  'settings.editor.fontFamilyHint': 'Eine kurze Liste; jeder Eintrag eine Familie, die jeder Rechner hat.',
  'settings.editor.font.serif': 'Serifen',
  'settings.editor.font.sans': 'Serifenlos',
  'settings.editor.font.mono': 'Festbreite',
  'settings.editor.fontSize': 'Grundgröße',
  'settings.editor.fontSizeHint': 'In Pixeln, {min} bis {max}. Überschriften behalten ihr Verhältnis dazu.',
  'settings.editor.wordWrap': 'Lange Zeilen umbrechen',
  'settings.editor.wordWrapHint': 'Die Vorgabe für jedes Blatt; ausgeschaltet läuft ein langer Absatz seitlich weiter.',
  'settings.editor.lineNumbers': 'Zeilennummern anzeigen',
  'settings.editor.lineNumbersHint':
    'Eine Spalte links der Überschriftenmarken. Eine umbrochene Zeile behält eine Nummer, und gezählt wird, was auch die Statusleiste nennt.',
  'settings.category.sheetList.label': 'Blattliste',
  'settings.category.sheetList.description': 'Wie die Blätter einer Gruppe in der Vorschau erscheinen.',
  'settings.category.outline.label': 'Gliederung',
  'settings.category.outline.description': 'Welche Überschriften die Gliederung auflistet.',
  'settings.category.frontMatter.label': 'Variablen',
  'settings.category.frontMatter.description':
    'Der Bereich über dem Text, der die Metadaten eines Blatts so zeigt, wie sie geschrieben sind.',
  'settings.category.pageCategories.label': 'Seitenkategorien',
  'settings.category.pageCategories.description':
    'Die Kategorien dieses Projekts. Sie gehören zum Projekt, nicht zu dieser Installation.',
  'settings.category.sourceControl.label': 'Versionsverwaltung',
  'settings.category.sourceControl.description':
    'Name und E-Mail-Adresse, unter denen Commits stehen, eingetragen im Repository dieses Projekts.',
  'settings.appearance.language': 'Sprache der Oberfläche',
  'settings.appearance.languageHint': 'Die nativen Menüs folgen sofort.',
  'settings.language.system': 'Dem System folgen',
  'settings.language.en': 'English',
  'settings.language.de': 'Deutsch',
  'settings.sheetList.density': 'Größe der Vorschau',
  'settings.sheetList.densityHint': 'Die kompakte Stufe zeigt jedes Blatt in derselben Höhe.',
  'settings.sheetList.density.compact': 'Kompakt',
  'settings.sheetList.density.standard': 'Standard',
  'settings.sheetList.density.large': 'Groß',
  'settings.sheetList.blankLines': 'Leerzeilen in der Vorschau zeigen',
  'settings.sheetList.blankLinesHint': 'Ausgeschaltet überspringt die Vorschau leere Zeilen, damit mehr Text hineinpasst.',
  'settings.outline.deeper': 'Überschriften unterhalb der zweiten Ebene auflisten',
  'settings.frontMatter.show': 'Den Variablenbereich zeigen',
  'settings.frontMatter.writable': 'Die fremden Zeilen bearbeitbar machen',
  'settings.frontMatter.writableHint': 'Die Zeilen, die dieser Anwendung gehören, sind dort nie bearbeitbar.',
  'settings.frontMatter.showOwned': 'Die Zeilen zeigen, die dieser Anwendung gehören',

  'welcome.tagline': 'Texte sammeln und schreiben, und ein Buch daraus wachsen lassen.',
  'welcome.open': 'Projekt öffnen…',
  'welcome.new': 'Neues Projekt…',
  'welcome.recent': 'Zuletzt geöffnet',
  'welcome.notFound': 'nicht gefunden',
  'welcome.remove': '{name} aus der Liste entfernen',
  'welcome.removeTitle': 'Aus der Liste entfernen',
  'welcome.empty': 'Noch kein Projekt geöffnet.',
  'welcome.gone': 'Dieses Projekt ist nicht mehr da. Entferne es aus der Liste oder stelle den Ordner wieder her.',
  'welcome.openFailed': 'Das Projekt ließ sich nicht öffnen ({code}).',
  'newProject.title': 'Neues Projekt',
  'newProject.name': 'Name',
  'newProject.namePlaceholder': 'Der Hafenroman',
  'newProject.location': 'Ort',
  'newProject.noFolder': 'Kein Ordner gewählt',
  'newProject.choose': 'Wählen…',
  'newProject.previewBefore': 'Legt den Ordner',
  'newProject.previewAfter': ' an. Der Name oben kann sich später ändern; der Ordnername nicht.',
  'newProject.failed': 'Das Projekt ließ sich nicht anlegen ({code}).',
  'openFolder.adoptTitle': 'Noch kein Projekt',
  'openFolder.adoptBody':
    '„{folder}“ enthält noch kein Projekt. Eines daraus machen? Die Texte darin bleiben, ' +
    'wie sie sind; das Projekt legt nur einen eigenen Ordner für seine Aufzeichnungen an.',
  'openFolder.adopt': 'Als Projekt verwenden',
  'openFolder.subprojectTitle': 'Das Projekt liegt eine Ebene tiefer',
  'openFolder.subprojectBody':
    'Dieser Ordner ist selbst kein Projekt, enthält aber eines: „{name}“. Öffnen?',
  'openFolder.severalTitle': 'Mehrere Projekte in diesem Ordner',
  'openFolder.severalBody':
    'Dieser Ordner ist selbst kein Projekt und enthält mehrere. Bitte das gemeinte direkt öffnen:',

  'menu.file': '&Datei',
  'menu.edit': '&Bearbeiten',
  'menu.window': '&Fenster',
  'menu.newProject': 'Neues Projekt…',
  'menu.openProject': 'Projekt öffnen…',
  'menu.save': 'Speichern',
  'menu.closeProject': 'Projekt schließen',
  'menu.settings': 'Einstellungen…',
};
