/**
 * The English catalogue: the base language, and the source of every key.
 * SPEC.md §14.1.
 *
 * Grouped by where the words appear. `{name}` is a placeholder; a key ending
 * in `.one` or `.other` is one form of a plural family and is read through
 * `plural()`, never directly.
 */
export const EN = {
  // --- views and the shell ---------------------------------------------------
  'view.explorer': 'Explorer',
  'view.sourceControl': 'Source control',
  'view.inspector': 'Inspector',
  'view.outline': 'Outline',
  'view.ai': 'AI assistant',
  'view.snapshots': 'Snapshots',
  'view.settings': 'Settings',

  'app.noProject': 'No project open.',
  'app.readOnly': 'read-only',
  'app.refresh': 'Refresh',
  'app.reload': 'Reload from disk',
  'app.frontMatter.show': 'Variables',
  'app.frontMatter.writable': 'Writable',
  'app.frontMatter.system': 'System',
  'app.frontMatter.foreign': 'Foreign front matter',
  'app.frontMatter.own': 'Own front matter',
  'app.selectSheet': 'Select a sheet to start writing.',
  'app.outline.deeper': 'H3–H6',
  'app.outline.deeperTitle': 'Show H3 to H6',
  'app.notBuilt': 'Not built yet.',
  'app.ignore.title': 'Ignored files',
  'app.ignore.hint': 'One path or pattern per line, as git reads them.',
  'app.conflict.title': 'This sheet changed on disk while you were editing it',
  'app.conflict.warning': 'Loading the file discards what you have not saved.',
  'app.conflict.hint': 'Keeping yours changes nothing on disk; saving afterwards overwrites the file.',
  'app.conflict.confirm': 'Load the file',
  'app.dismiss': 'Dismiss',

  // --- shared buttons --------------------------------------------------------
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.open': 'Open',
  'common.save': 'Save',
  'common.create': 'Create',
  'common.rename': 'Rename',
  'common.delete': 'Delete',
  'common.discard': 'Discard',
  'confirm.trashHint': 'It goes to the desktop trash, where it can be restored.',

  // --- the editor ------------------------------------------------------------
  'heading.none': 'No heading',
  'statusBar.position': 'Ln {line}, Col {column}',
  'statusBar.positionLabel': 'Cursor position',
  'statusBar.wrap': 'Wrap',
  'statusBar.wrapTitle': 'Wrap long lines in this sheet',
  'statusBar.zoom': '{percent} %',
  'statusBar.zoomLabel': 'Editor zoom',
  'statusBar.zoomResetTitle': 'Back to 100 %',
  'outline.empty': 'No headings in this sheet.',
  'sheetList.empty': 'No sheets in this group.',

  // --- the inspector ---------------------------------------------------------
  'inspector.words.one': 'word',
  'inspector.words.other': 'words',
  'inspector.characters.one': 'character',
  'inspector.characters.other': 'characters',
  'inspector.minutes.one': 'min reading',
  'inspector.minutes.other': 'min reading',
  'inspector.title': 'Title',
  'inspector.topic': 'Topic',
  'inspector.topicPlaceholder': 'one short label',
  'inspector.keywords': 'Keywords',
  'inspector.keywordsPlaceholder': 'comma separated',
  'inspector.status': 'Status',
  'inspector.category': 'Category',
  'inspector.noCategory': 'None',
  'inspector.manage': 'Manage…',
  'inspector.notes': 'Notes',
  'inspector.notesPlaceholder': 'research, open questions, reminders',
  'inspector.noSheet': 'No sheet open.',

  // --- page categories -------------------------------------------------------
  'categories.title': 'Page categories',
  'categories.empty': 'No categories yet.',
  'categories.add': 'Add',
  'categories.colourOf': 'Colour of {name}',
  'categories.name': 'Category name',
  'categories.delete': 'Delete category',
  'categories.unnamed': 'Unnamed',
  'categories.new': 'New category',
  'categories.limit': 'A project holds at most {limit} categories.',

  // --- library menus and prompts ---------------------------------------------
  'library.menu.newSheet': 'New Sheet…',
  'library.menu.newGroup': 'New Group…',
  'library.menu.rename': 'Rename…',
  'library.menu.deleteGroup': 'Delete Group…',
  'library.menu.deleteSheet': 'Delete Sheet…',
  'library.newSheet.title': 'New sheet',
  'library.newSheet.placeholder': 'The First Scene',
  'library.newSheet.hint': 'The title can change later; the file name is set once, from it.',
  'library.newGroup.title': 'New group',
  'library.newGroup.placeholder': 'Part One',
  'library.newGroup.hint': 'The name can change later; the folder name is set once, from it.',
  'library.renameGroup.title': 'Rename group',
  'library.renameGroup.hint': 'Renaming changes the name shown here, never the folder on disk.',
  'library.renameSheet.title': 'Rename sheet',
  'library.renameSheet.hint': 'Renaming changes the title in the file, never the file name.',
  'library.trash.title': 'Move “{name}” to the trash?',
  'library.trash.unsaved': 'It has unsaved changes, and those are not in the trash afterwards.',
  'library.trash.contents': 'Everything in it goes too: {parts}.',
  'library.trash.and': ' and ',
  'library.sheets.one': '{count} sheet',
  'library.sheets.other': '{count} sheets',
  'library.subgroups.one': '{count} subgroup',
  'library.subgroups.other': '{count} subgroups',

  // --- source control --------------------------------------------------------
  'sourceControl.noRepository': 'This project is not inside a Git repository.',
  'sourceControl.createRepository': 'Create repository',
  'sourceControl.reading': 'Reading…',
  'sourceControl.onBranch': 'On branch {name}',
  'sourceControl.branches': 'Branches…',
  'sourceControl.notPublished': '{branch} — not published',
  'sourceControl.publish': 'Publish branch…',
  'sourceControl.tracking': 'Tracking {upstream}',
  'sourceControl.upToDate': 'up to date',
  'sourceControl.fetch': 'Fetch',
  'sourceControl.pull': 'Pull',
  'sourceControl.merge': 'Merge…',
  'sourceControl.merging': 'Merge in progress. Decide each conflict, then commit.',
  'sourceControl.abortMerge': 'Abort merge',
  'sourceControl.noAuthor': 'Commits have no author yet.',
  'sourceControl.setIdentity': 'Set…',
  'sourceControl.ignoredFiles': 'Ignored files…',
  'sourceControl.stageAll': 'Stage all changes',
  'sourceControl.changes': 'Changes ({count})',
  'sourceControl.stage': 'Stage {path}',
  'sourceControl.ignore': 'Ignore {path}',
  'sourceControl.ignoreTitle': 'Add to .gitignore',
  'sourceControl.resolve': 'Resolve {path}',
  'sourceControl.resolveTitle': 'Resolve this conflict',
  'sourceControl.resolveButton': 'Resolve…',
  'sourceControl.showChanges': 'Show changes to {path}',
  'sourceControl.showChangesTitle': 'Show changes',
  'sourceControl.discardChanges': 'Discard changes to {path}',
  'sourceControl.discardTitle': 'Discard changes',
  'sourceControl.nothingChanged': 'Nothing has changed.',
  'sourceControl.messagePlaceholder': 'Commit message',
  'sourceControl.amend': 'Amend last commit…',
  'sourceControl.commit': 'Commit',
  'sourceControl.commitAndPush': 'Commit and push',
  'sourceControl.gitNotInstalled':
    'Git is not installed on this machine, or not on the path. Source control needs it; everything else works without it.',

  'discard.title': 'Discard the changes to “{path}”?',
  'discard.untracked':
    'This file is not in the repository yet, so there is nothing to go back to: it goes to the trash.',
  'discard.tracked':
    'The file goes back to its last committed state, and unsaved changes to it in the editor go with it.',
  'discard.historyHint': 'The committed version stays in the repository’s history either way.',
  'merge.title': 'Merge the changes from the remote?',
  'merge.warning': 'Where both sides changed the same passage, you decide which version stays.',
  'merge.hint': 'A merge can be abandoned afterwards, putting everything back as it was.',
  'merge.confirm': 'Merge',
  'publish.title': 'Publish this branch',
  'publish.placeholder': 'https://example.com/book.git',
  'publish.hint': 'The address of an empty repository. It is recorded as “origin”.',
  'publish.confirm': 'Publish',
  'publish.toTitle': 'Publish “{branch}” to {remote}?',
  'publish.toWarning': 'Everything committed on this branch is sent to {url}.',
  'publish.toHint': 'From then on, Commit and push goes there without asking again.',
  'switch.title': 'Save or discard first',
  'switch.warning': '“{title}” has changes that are not saved.',
  'switch.hint': 'Switching branches replaces files on disk, and unsaved work has nowhere to go.',
  'switch.confirm': 'Save and switch',
  'newBranch.title': 'New branch',
  'newBranch.placeholder': 'draft/chapter-3',
  'newBranch.hint': 'It starts at the current commit, and is switched to at once.',
  'deleteBranch.title': 'Delete the branch “{name}”?',
  'deleteBranch.warning':
    'Only a branch whose work is already merged can be deleted; git refuses the rest.',
  'deleteBranch.hint': 'The commits stay in the repository either way.',
  'amend.title': 'Replace the last commit?',
  'amend.warning': 'It is rewritten with whatever is staged, and its message becomes “{message}”.',
  'amend.hint': 'Offered only while it has not been pushed; afterwards it could only be replaced by force.',
  'amend.confirm': 'Amend',

  'branches.title': 'Branches',
  'branches.new': 'New branch…',
  'branches.checkedOut': 'checked out',
  'branches.switch': 'Switch',
  'branches.delete': 'Delete…',
  'branches.empty': 'This repository has no branch yet.',

  'resolver.label': 'Resolve {path}',
  'resolver.decided': '{decided} of {total} decided',
  'resolver.apply': 'Apply',
  'resolver.keepMine': 'Keep mine',
  'resolver.takeTheirs': 'Take theirs',

  'diff.words': 'Words',
  'diff.lines': 'Lines',
  'diff.nothing': 'Nothing changed in this file.',
  'diff.gitNothing': 'Git reports no difference for this file.',
  'diff.wordsLabel': 'Changes, word by word',
  'diff.label': 'Diff',

  // --- the identity question -------------------------------------------------
  'identity.title': 'Name and e-mail for commits',
  'identity.name': 'Name',
  'identity.email': 'E-mail',
  'identity.hint':
    'Both are written into every commit and go with the manuscript wherever it is published. They are recorded in this project only; nothing outside it changes.',
  'identity.notNow': 'Not now',

  // --- settings --------------------------------------------------------------
  'settings.title': 'Settings',
  'settings.categories': 'Settings categories',
  'settings.manageCategories': 'Manage categories…',
  'settings.identity.local': 'Recorded in this repository.',
  'settings.identity.global':
    'From your global Git configuration; saving here records a copy in this repository.',
  'settings.identity.none': 'Commits have no author yet.',
  'settings.reset': 'Reset all settings',
  'settings.applyNote': 'Changes apply at once and are kept for this installation.',
  'settings.category.appearance.label': 'Appearance',
  'settings.category.appearance.description': 'The language the interface speaks.',
  'settings.category.editor.label': 'Editor',
  'settings.category.editor.description': 'How the text reads while you write it.',
  'settings.editor.fontFamily': 'Font',
  'settings.editor.fontFamilyHint': 'A short list, each entry a family every machine has.',
  'settings.editor.font.serif': 'Serif',
  'settings.editor.font.sans': 'Sans-serif',
  'settings.editor.font.mono': 'Monospace',
  'settings.editor.fontSize': 'Base size',
  'settings.editor.fontSizeHint': 'In pixels, {min} to {max}. Headings keep their ratios to it.',
  'settings.editor.wordWrap': 'Wrap long lines',
  'settings.editor.wordWrapHint': 'The default for every sheet; off, a long paragraph scrolls sideways.',
  'settings.editor.lineNumbers': 'Show line numbers',
  'settings.editor.lineNumbersHint':
    'A column left of the heading markers. A wrapped line keeps one number, and the count is the one the status bar names.',
  'settings.category.sheetList.label': 'Sheet list',
  'settings.category.sheetList.description': 'How the sheets of a group are previewed.',
  'settings.category.outline.label': 'Outline',
  'settings.category.outline.description': 'Which headings the outline pane lists.',
  'settings.category.frontMatter.label': 'Front matter',
  'settings.category.frontMatter.description':
    'The area above the text that shows a sheet’s metadata as written.',
  'settings.category.pageCategories.label': 'Page categories',
  'settings.category.pageCategories.description':
    'The categories of this project. They live with the project, not with this installation.',
  'settings.category.sourceControl.label': 'Source control',
  'settings.category.sourceControl.description':
    'The name and e-mail address commits are by, recorded in this project’s repository.',
  'settings.appearance.language': 'Interface language',
  'settings.appearance.languageHint': 'The native menus follow at once.',
  'settings.appearance.colorScheme': 'Appearance',
  'settings.appearance.colorSchemeHint': 'Following the system means changing with it, whenever it changes.',
  'settings.colorScheme.system': 'Follow the system',
  'settings.colorScheme.light': 'Light',
  'settings.colorScheme.dark': 'Dark',
  'settings.appearance.accentPalette': 'Accent colour',
  'settings.appearance.accentPaletteHint': 'The one colour that marks what is selected, active, or focused.',
  'settings.palette.blue': 'Blue',
  'settings.palette.gray': 'Grey',
  'settings.palette.yellow': 'Yellow',
  'settings.palette.green': 'Green',
  'settings.palette.violet': 'Violet',
  'settings.palette.red': 'Red',
  'settings.palette.orange': 'Orange',
  'settings.palette.turquoise': 'Turquoise',
  'settings.language.system': 'Follow the system',
  'settings.language.en': 'English',
  'settings.language.de': 'Deutsch',
  'settings.sheetList.density': 'Preview size',
  'settings.sheetList.densityHint': 'The compact step shows every sheet at the same height.',
  'settings.sheetList.density.compact': 'Compact',
  'settings.sheetList.density.standard': 'Standard',
  'settings.sheetList.density.large': 'Large',
  'settings.sheetList.blankLines': 'Show blank lines in previews',
  'settings.sheetList.blankLinesHint': 'Off, a preview skips empty lines so more of the text fits.',
  'settings.outline.deeper': 'List headings below the second level',
  'settings.frontMatter.show': 'Show the front matter area',
  'settings.frontMatter.writable': 'Allow editing the foreign lines',
  'settings.frontMatter.writableHint': 'The lines this application owns are never editable there.',
  'settings.frontMatter.showOwned': 'Show the lines this application owns',

  // --- the launcher ----------------------------------------------------------
  'welcome.tagline': 'Collect and write texts, and grow a book out of them.',
  'welcome.open': 'Open project…',
  'welcome.new': 'New project…',
  'welcome.recent': 'Recent projects',
  'welcome.notFound': 'not found',
  'welcome.remove': 'Remove {name} from the list',
  'welcome.removeTitle': 'Remove from list',
  'welcome.empty': 'No projects opened yet.',
  'welcome.gone': 'That project is no longer there. Remove it from the list, or restore the folder.',
  'welcome.openFailed': 'Could not open the project ({code}).',
  'newProject.title': 'New project',
  'newProject.name': 'Name',
  'newProject.namePlaceholder': 'The Harbour Novel',
  'newProject.location': 'Location',
  'newProject.noFolder': 'No folder chosen',
  'newProject.choose': 'Choose…',
  'newProject.previewBefore': 'Creates the folder',
  'newProject.previewAfter': '. The name above can change later; the folder name cannot.',
  'newProject.failed': 'Could not create the project ({code}).',
  'openFolder.adoptTitle': 'Not a project yet',
  'openFolder.adoptBody':
    '“{folder}” holds no project. Make it one? The texts in it stay exactly as they are; ' +
    'the project only adds a folder of its own for what it has to remember.',
  'openFolder.adopt': 'Use as project',
  'openFolder.subprojectTitle': 'The project is one level down',
  'openFolder.subprojectBody':
    'This folder is not a project itself, but it holds one: “{name}”. Open it?',
  'openFolder.severalTitle': 'Several projects in this folder',
  'openFolder.severalBody':
    'This folder is not a project itself, and it holds several. Open the one you mean directly:',

  // --- the native menu -------------------------------------------------------
  'menu.file': '&File',
  'menu.edit': '&Edit',
  'menu.window': '&Window',
  'menu.newProject': 'New Project…',
  'menu.openProject': 'Open Project…',
  'menu.save': 'Save',
  'menu.closeProject': 'Close Project',
  'menu.settings': 'Settings…',
} as const;
